### ISSUE TITLE
D key is not handled when pressed

### ISSUE THREAD

**Issue by hvox** [CommanderRag/xbox-controller-emulator-linux#1]
https://github.com/CommanderRag/xbox-controller-emulator-linux/blob/69b8eb07338cc90a61916a31e931d6e6eebdeacd/emulator.cpp#L360-L365
Pressing or holding down the WASD keys results in using the gamepad joystick, but the D key is only accepted when it is held down: single presses do not work. Why is the D treated differently than the WAS?

**Comment by CommanderRag** [comment]
I forgot to add single press to D key. Thanks for telling!
